<?xml version="1.0"?>	
<!DOCTYPE stock[	
<!ELEMENT stock (new-car|used-car)*>	
<!ELEMENT new-car (model,price)>	
<!ELEMENT used-car (model,price,mileage,condition?)>	
<!ELEMENT model (#PCDATA)>	
<!ELEMENT price (#PCDATA)>	
<!ELEMENT mileage (#PCDATA)>	
<!ELEMENT condition (#PCDATA)>	
]>

<stock>
    <new-car>
        <model>Mercedes</model>
        <price>40000</price>
    </new-car>
    <used-car>
        <model>BMW</model>
        <price>25000</price>
        <mileage>120000</mileage>
    </used-car>
</stock>