=== caarlosf/VSC_LMSXI/2Trim/XML/exer18.dtd
<!ELEMENT computer_shop (products,customers,sales)>
<!ELEMENT products (product+)>
<!ELEMENT product (title,(brand|manufacturer),model,price,stock,reconditioned?)>
<!ATTLIST product idP CDATA #REQUIRED>
<!ATTLIST product EAN CDATA #IMPLIED>
<!ELEMENT title EMPTY>
<!ELEMENT brand EMPTY>
<!ELEMENT model EMPTY>
<!ELEMENT price EMPTY>
<!ATTLIST price currency (EUR|USD) #REQUIRED>
<!ATTLIST price discount NMTOKEN "0">
<!ATTLIST price VAT (general | reduced | super-reduced) #REQUIRED>
<!ELEMENT stock EMPTY>
<!ELEMENT reconditioned EMPTY>
<!ELEMENT customers (customer*)>
<!ELEMENT customer (IDcard,((first_name,surnames)|complete_name),telephone_number*,postal_address?)>
<!ATTLIST customer idC CDATA #REQUIRED>
<!ATTLIST customer date_creation CDATA #REQUIRED>
<!ELEMENT IDcard EMPTY>
<!ELEMENT first_name EMPTY>
<!ELEMENT surnames EMPTY>
<!ELEMENT telephone_number EMPTY>
<!ELEMENT postal_address EMPTY>
<!ELEMENT sales (sale*)>
<!ELEMENT sale (list_of_products,total_price,currency)>
<!ATTLIST sale date_of_sale CDATA #REQUIRED>
<!ATTLIST sale customer CDATA #REQUIRED>
<!ELEMENT list_of_products EMPTY>
<!ATTLIST list_of_products id CDATA #REQUIRED>
<!ATTLIST list_of_products quantity CDATA #IMPLIED>
<!ELEMENT total_price EMPTY>
<!ELEMENT currency EMPTY>

=== caarlosf/VSC_LMSXI/2Trim/XML/exer18.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE computer_shop SYSTEM "exer18.dtd">
<computer_shop>
    <products>
        <product idP="" EAN="">
            <title></title>
            <brand></brand>
            <model></model>
            <price currency="EUR" discount="0" VAT="general"></price>
            <stock></stock>
            <reconditioned />
        </product>
    </products>
    <customers>
        <customer idC="" date_creation="">
            <IDcard></IDcard>
            <first_name></first_name>
            <surnames></surnames>
            <telephone_number></telephone_number>
            <postal_address></postal_address>
        </customer>
    </customers>
    <sales>
        <sale date_of_sale="" customer="">
            <list_of_products id="" quantity=""></list_of_products>
            <total_price></total_price>
            <currency></currency>

        </sale>
    </sales>

</computer_shop>
