=== caarlosf/VSC_LMSXI/2Trim/XML/films.dtd
<!ELEMENT films (film*,filmmaker*,info)>
<!ELEMENT film (name)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST film id ID #REQUIRED>
<!ATTLIST film maker IDREF #IMPLIED>
<!ELEMENT filmmaker (name)>
<!ATTLIST filmmaker id ID #REQUIRED>
<!ELEMENT info (#PCDATA|important)*>
    <!--sempre que sexa un elemento mixto (<important/>)
    (sÃ³ se pecha, non se abre e se pecha) 
    tense que declarar desta forma, (#PCDATA|important)*-->
<!ELEMENT important EMPTY>

=== caarlosf/VSC_LMSXI/2Trim/XML/films.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE films SYSTEM "films.dtd">
<!-- Insert SYSTEM DOCTYPE-->
<films>
    <film id="F1" maker="FM1">
            <!-- Non se pode poñer unicamente número, ten que ter unha letra antes, senon da erro-->
        <name>Forest Gump</name>
    </film>
    <film id="F2" maker="FM2">
        <name>War of the worlds</name>
    </film>
    <film id="F3" maker="FM3">
        <name>American psyco</name>
    </film>
    <filmmaker id="FM1">
        <name>Robert Zemeckys</name>
    </filmmaker>
    <filmmaker id="FM2">
        <name>Steven Spielberg</name>
    </filmmaker>
    <filmmaker id="FM3">
        <name>Mary Harron</name>
    </filmmaker>
    <info>
        <important/>
        This films are really interesting
    </info>
</films>
